apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cdtroman/gitops-example-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          envFrom:
            # Created by environment kustomize overlay
            - configMapRef:
                name: frontend-config

      imagePullSecrets:
        - name: fontend-docker-regcred
