apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cdtroman/gitops-example-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            # Created by environment kustomize overlay
            - configMapRef:
                name: backend-config

      imagePullSecrets:
        - name: backend-docker-regcred
