apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend
  - config.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    path: patches.yaml

images:
  - name: cdtroman/gitops-example-backend
    newTag: v0.1.0
